################################################################################
#
# Description: This script defines the project pipeline - it specifys the
#              execution orders for all the code in this repo using a series of
#              actions.
#
# Author(s): J.Mutio, M Green
# Date last updated: 22/02/2024
#
################################################################################

version: '3.0'

expectations:
  population_size: 1000

actions:

  # Extract data ----
  generate_dataset:
    run: >
      ehrql:v0 generate-dataset analysis/dataset_definition.py
      --output 'output/dataset.csv.gz'
    outputs:
      highly_sensitive:
        csv: output/dataset.csv.gz
      