version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: ehrql:v0 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv.gz

  initial_analysis:
    run: r:latest analysis/analysis.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        first_crosstab: output/first_crosstab.csv